### ISSUE TITLE
publish to maven central

### ISSUE THREAD

**Issue by szczebel** [fabianlinz/serenity-junit5#11]
I'd love my team to start playing with this module, although prefer to avoid aksing everyone to clone, build and install in local/provate maven repo. Any chance to get it published to maven central?

It might help with feedback and identification of gaps&issues.

**Comment by fabianlinz** [comment]
@szczebel sorry for not getting back to you in time. Fully agree that having builds published to maven central makes trying it out a lot easier. Did you have a chance to play with it nevertheless? 

Releases are now published to Maven Central (https://search.maven.org/search?q=g:io.github.fabianlinz%20AND%20a:serenity-junit5)
