### ISSUE TITLE
Upgrade to serenity-core version without runtime dependency on JUnit4

### ISSUE THREAD

**Issue by fabianlinz** [fabianlinz/serenity-junit5#3]
From the readme...
* serenity-core and serenity-model have dependencies to JUnit4, which has several implications.
    * At runtime JUnit4 is currently still needed.
    * serenity-core and serenity-model should be changed such that JUnit4 is an optional dependency.
* Automatically taking screenshot for web tests
    * Screenshots are only taken if `TestCaseAnnotations.isASerenityTestCase` is true. Currently this method only works for JUnit4 tests as
    it checks for the annotation `@RunWith`   
    * Workaround: Tests can extend `net.serenitybdd.junit5.AbstractSerenityTestDetectionWorkaround`

**Comment by fabianlinz** [comment]
Issue in serenity-core: https://github.com/serenity-bdd/serenity-core/issues/1858

**Comment by amohrig** [comment]
Hi @fabianlinz ,

I created branch upgrade_serenity_core and pushed a first attempt.
